<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrecosBaseSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('precos_base')->insert([
            [
                'prc_cod_prod'     => ' PRD001 ',
                'prc_valor'        => ' 499,90 ',
                'prc_moeda'        => 'brl',
                'prc_desc'         => '5%',
                'prc_acres'        => '0',
                'prc_promo'        => '474,90',
                'prc_dt_ini_promo' => '2025/10/10',
                'prc_dt_fim_promo' => '2025-10-20',
                'prc_dt_atual'     => '2025-10-15',
                'prc_origem'       => 'SISTEMA ERP',
                'prc_tipo_cli'     => 'VAREJO',
                'prc_vend_resp'    => 'Marcos Silva',
                'prc_obs'          => 'Produto em destaque',
                'prc_status'       => 'ativo',
            ],
            [
                'prc_cod_prod'     => 'prd002',
                'prc_valor'        => '120.50',
                'prc_moeda'        => 'BRL ',
                'prc_desc'         => ' 0',
                'prc_acres'        => '0',
                'prc_promo'        => '120.50',
                'prc_dt_ini_promo' => '10-10-2025',
                'prc_dt_fim_promo' => null,
                'prc_dt_atual'     => '2025-10-16',
                'prc_origem'       => 'MIGRACAO',
                'prc_tipo_cli'     => 'ATACADO',
                'prc_vend_resp'    => ' Julia S.',
                'prc_obs'          => null,
                'prc_status'       => 'ativo',
            ],
            [
                'prc_cod_prod'     => 'PRD003',
                'prc_valor'        => '1.099,00',
                'prc_moeda'        => 'brl ',
                'prc_desc'         => '10%',
                'prc_acres'        => null,
                'prc_promo'        => '989,10',
                'prc_dt_ini_promo' => '2025.10.10',
                'prc_dt_fim_promo' => '2025.10.25',
                'prc_dt_atual'     => '16/10/2025',
                'prc_origem'       => 'API INTERNA',
                'prc_tipo_cli'     => 'VAREJO',
                'prc_vend_resp'    => ' Carlos Souza ',
                'prc_obs'          => 'Desconto aplicado via API',
                'prc_status'       => 'ativo',
            ],
            [
                'prc_cod_prod'     => ' prd004',
                'prc_valor'        => ' 899.99',
                'prc_moeda'        => 'brl',
                'prc_desc'         => null,
                'prc_acres'        => '5%',
                'prc_promo'        => null,
                'prc_dt_ini_promo' => '15/10/2025',
                'prc_dt_fim_promo' => '30/10/2025',
                'prc_dt_atual'     => '2025/10/16',
                'prc_origem'       => 'ERP LEGADO',
                'prc_tipo_cli'     => 'VAREJO',
                'prc_vend_resp'    => 'Jéssica M.',
                'prc_obs'          => 'Campanha de Outubro',
                'prc_status'       => 'ativo',
            ],
            [
                'prc_cod_prod'     => 'PRD005 ',
                'prc_valor'        => 'sem preço',
                'prc_moeda'        => 'BRL',
                'prc_desc'         => null,
                'prc_acres'        => null,
                'prc_promo'        => null,
                'prc_dt_ini_promo' => null,
                'prc_dt_fim_promo' => null,
                'prc_dt_atual'     => '2025-10-10',
                'prc_origem'       => 'ERP LEGADO',
                'prc_tipo_cli'     => 'VAREJO',
                'prc_vend_resp'    => 'Pedro L.',
                'prc_obs'          => 'Sem preço cadastrado',
                'prc_status'       => 'inativo',
            ],
            [
                'prc_cod_prod'     => 'PRD006',
                'prc_valor'        => '389,90',
                'prc_moeda'        => 'BRL',
                'prc_desc'         => '15%',
                'prc_acres'        => '2%',
                'prc_promo'        => '331,42',
                'prc_dt_ini_promo' => '2024.06.01',
                'prc_dt_fim_promo' => '2024.06.30',
                'prc_dt_atual'     => '2024-05-28',
                'prc_origem'       => 'SISTEMA ERP',
                'prc_tipo_cli'     => 'VAREJO',
                'prc_vend_resp'    => 'Ana Costa',
                'prc_obs'          => 'Promoção semestral',
                'prc_status'       => 'ativo',
            ],
            [
                'prc_cod_prod'     => 'PRD007',
                'prc_valor'        => '2.899,00',
                'prc_moeda'        => 'brl',
                'prc_desc'         => '8%',
                'prc_acres'        => null,
                'prc_promo'        => '2.667,08',
                'prc_dt_ini_promo' => '2024/04/15',
                'prc_dt_fim_promo' => '2024/05/15',
                'prc_dt_atual'     => '2024-04-10',
                'prc_origem'       => 'API INTERNA',
                'prc_tipo_cli'     => 'ATACADO',
                'prc_vend_resp'    => 'Roberto Lima',
                'prc_obs'          => 'Desconto por volume',
                'prc_status'       => 'ativo',
            ],
            [
                'prc_cod_prod'     => 'PRD008',
                'prc_valor'        => '1.899,00',
                'prc_moeda'        => 'BRL',
                'prc_desc'         => '12%',
                'prc_acres'        => '3%',
                'prc_promo'        => '1.671,12',
                'prc_dt_ini_promo' => '2024-03-01',
                'prc_dt_fim_promo' => '2024-03-31',
                'prc_dt_atual'     => '2024.02.25',
                'prc_origem'       => 'ERP LEGADO',
                'prc_tipo_cli'     => 'VAREJO',
                'prc_vend_resp'    => 'Fernanda R.',
                'prc_obs'          => 'Liquidação estoque',
                'prc_status'       => 'ativo',
            ],
            [
                'prc_cod_prod'     => 'PRD009',
                'prc_valor'        => '299,90',
                'prc_moeda'        => 'brl',
                'prc_desc'         => '20%',
                'prc_acres'        => '0',
                'prc_promo'        => '239,92',
                'prc_dt_ini_promo' => '2024.05.20',
                'prc_dt_fim_promo' => '2024.06.20',
                'prc_dt_atual'     => '2024/05/15',
                'prc_origem'       => 'SISTEMA ERP',
                'prc_tipo_cli'     => 'ATACADO',
                'prc_vend_resp'    => 'Carlos Santos',
                'prc_obs'          => 'Queima de estoque',
                'prc_status'       => 'ativo',
            ],
            [
                'prc_cod_prod'     => 'PRD010',
                'prc_valor'        => '699,00',
                'prc_moeda'        => 'BRL',
                'prc_desc'         => '5%',
                'prc_acres'        => '1%',
                'prc_promo'        => '664,05',
                'prc_dt_ini_promo' => '2024-04-01',
                'prc_dt_fim_promo' => '2024-04-30',
                'prc_dt_atual'     => '2024-03-28',
                'prc_origem'       => 'API INTERNA',
                'prc_tipo_cli'     => 'VAREJO',
                'prc_vend_resp'    => 'Mariana O.',
                'prc_obs'          => 'Promoção relâmpago',
                'prc_status'       => 'ativo',
            ],
            [
                'prc_cod_prod'     => 'PRD011',
                'prc_valor'        => '450,00',
                'prc_moeda'        => 'brl',
                'prc_desc'         => '25%',
                'prc_acres'        => null,
                'prc_promo'        => '337,50',
                'prc_dt_ini_promo' => '2024/06/10',
                'prc_dt_fim_promo' => '2024/07/10',
                'prc_dt_atual'     => '2024.06.05',
                'prc_origem'       => 'ERP LEGADO',
                'prc_tipo_cli'     => 'VAREJO',
                'prc_vend_resp'    => 'Paulo H.',
                'prc_obs'          => 'Dia dos namorados',
                'prc_status'       => 'ativo',
            ],
            [
                'prc_cod_prod'     => 'PRD012',
                'prc_valor'        => '0',
                'prc_moeda'        => 'BRL',
                'prc_desc'         => null,
                'prc_acres'        => null,
                'prc_promo'        => null,
                'prc_dt_ini_promo' => null,
                'prc_dt_fim_promo' => null,
                'prc_dt_atual'     => '2024-03-20',
                'prc_origem'       => 'SISTEMA ERP',
                'prc_tipo_cli'     => 'VAREJO',
                'prc_vend_resp'    => 'Lucas T.',
                'prc_obs'          => 'Produto descontinuado',
                'prc_status'       => 'inativo',
            ],
        ]);
    }
}
