<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdutosBaseSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('produtos_base')->insert([
            [
                'prod_cod'    => ' PRD001',
                'prod_nome'   => '   Teclado  Mecânico   RGB  ',
                'prod_cat'    => 'PERIFERICOS',
                'prod_subcat' => 'TECLADOS',
                'prod_desc'   => 'Teclado com iluminação RGB e switches azuis',
                'prod_fab'    => 'HyperTech',
                'prod_mod'    => 'HT-KEY-RGB',
                'prod_cor'    => 'Preto',
                'prod_peso'   => '1,2kg ',
                'prod_larg'   => '45 cm',
                'prod_alt'    => '5 CM ',
                'prod_prof'   => '15cm ',
                'prod_und'    => 'UN ',
                'prod_atv'    => true,
                'prod_dt_cad' => '2025/10/10',
            ],
            [
                'prod_cod'    => 'prd002 ',
                'prod_nome'   => ' Mouse óptico  sem fio',
                'prod_cat'    => 'Periféricos ',
                'prod_subcat' => 'Mouses',
                'prod_desc'   => 'Mouse com conexão wireless 2.4GHz',
                'prod_fab'    => 'TechPro',
                'prod_mod'    => 'TP-MOUSE-X',
                'prod_cor'    => ' Preto ',
                'prod_peso'   => ' 95g ',
                'prod_larg'   => '6cm',
                'prod_alt'    => '3 CM',
                'prod_prof'   => '10cm',
                'prod_und'    => ' un',
                'prod_atv'    => true,
                'prod_dt_cad' => '10-10-2025',
            ],
            [
                'prod_cod'    => 'PRD003',
                'prod_nome'   => 'Monitor 24" Full HD',
                'prod_cat'    => 'MONITORES',
                'prod_subcat' => 'LCD',
                'prod_desc'   => 'Monitor 1080p HDMI e VGA',
                'prod_fab'    => 'ViewBest',
                'prod_mod'    => 'VB-24HD',
                'prod_cor'    => 'Preto',
                'prod_peso'   => '3.5 KG',
                'prod_larg'   => '53,2cm ',
                'prod_alt'    => '32cm ',
                'prod_prof'   => ' 12 cm ',
                'prod_und'    => 'un',
                'prod_atv'    => true,
                'prod_dt_cad' => '2025-10-12',
            ],
            [
                'prod_cod'    => 'PRD004',
                'prod_nome'   => 'Cadeira gamer Reclinável ',
                'prod_cat'    => 'Móveis ',
                'prod_subcat' => 'Cadeiras',
                'prod_desc'   => 'Cadeira ergonômica com apoio de braço',
                'prod_fab'    => 'ComfortSeat',
                'prod_mod'    => 'CS-GAMER-R',
                'prod_cor'    => 'Vermelha',
                'prod_peso'   => ' 16,3 kg',
                'prod_larg'   => '70 CM ',
                'prod_alt'    => ' 120 cm',
                'prod_prof'   => '60 CM',
                'prod_und'    => 'UN',
                'prod_atv'    => true,
                'prod_dt_cad' => '15/10/2025',
            ],
            [
                'prod_cod'    => ' PRD005',
                'prod_nome'   => 'HEADSET gamer 7.1',
                'prod_cat'    => 'Periféricos',
                'prod_subcat' => 'Headsets',
                'prod_desc'   => 'Headset com som surround 7.1 e microfone retrátil',
                'prod_fab'    => 'SoundMax',
                'prod_mod'    => 'SM-HS71',
                'prod_cor'    => ' Preto ',
                'prod_peso'   => ' 350G ',
                'prod_larg'   => '18cm',
                'prod_alt'    => '20 CM ',
                'prod_prof'   => '10 cm',
                'prod_und'    => 'UN',
                'prod_atv'    => false,
                'prod_dt_cad' => '2025.10.09',
            ],
            [
                'prod_cod'    => 'PRD006',
                'prod_nome'   => 'SSD 1TB NVMe',
                'prod_cat'    => 'COMPONENTES',
                'prod_subcat' => 'ARMAZENAMENTO',
                'prod_desc'   => 'SSD NVMe M.2 2280, leitura 3500MB/s',
                'prod_fab'    => 'DataFast',
                'prod_mod'    => 'DF-NV1TB',
                'prod_cor'    => 'Prata',
                'prod_peso'   => '8g',
                'prod_larg'   => '8cm',
                'prod_alt'    => '0,2cm',
                'prod_prof'   => '2,2cm',
                'prod_und'    => 'UN',
                'prod_atv'    => true,
                'prod_dt_cad' => '2023-05-20',
            ],
            [
                'prod_cod'    => 'PRD007',
                'prod_nome'   => 'Placa de Vídeo RTX 4060',
                'prod_cat'    => 'COMPONENTES',
                'prod_subcat' => 'GPUS',
                'prod_desc'   => '8GB GDDR6, 3072 cores CUDA',
                'prod_fab'    => 'GraphiCore',
                'prod_mod'    => 'GC-RTX4060',
                'prod_cor'    => 'Preto',
                'prod_peso'   => '1.2kg',
                'prod_larg'   => '24cm',
                'prod_alt'    => '11.5cm',
                'prod_prof'   => '4cm',
                'prod_und'    => 'UN',
                'prod_atv'    => true,
                'prod_dt_cad' => '2024/01/15',
            ],
            [
                'prod_cod'    => 'PRD008',
                'prod_nome'   => 'Processador Core i7',
                'prod_cat'    => 'COMPONENTES',
                'prod_subcat' => 'CPUS',
                'prod_desc'   => '12ª geração, 12 núcleos, 4.9GHz',
                'prod_fab'    => 'ChipTech',
                'prod_mod'    => 'CT-I712700',
                'prod_cor'    => 'Prata',
                'prod_peso'   => '50g',
                'prod_larg'   => '4.5cm',
                'prod_alt'    => '4.5cm',
                'prod_prof'   => '0.5cm',
                'prod_und'    => 'UN',
                'prod_atv'    => true,
                'prod_dt_cad' => '2023.11.30',
            ],
            [
                'prod_cod'    => 'PRD009',
                'prod_nome'   => 'Memória RAM 16GB',
                'prod_cat'    => 'COMPONENTES',
                'prod_subcat' => 'MEMORIAS',
                'prod_desc'   => 'DDR4 3200MHz, CL16',
                'prod_fab'    => 'MemSpeed',
                'prod_mod'    => 'MS-D416G',
                'prod_cor'    => 'Preta',
                'prod_peso'   => '40g',
                'prod_larg'   => '13.3cm',
                'prod_alt'    => '3cm',
                'prod_prof'   => '0.8cm',
                'prod_und'    => 'UN',
                'prod_atv'    => true,
                'prod_dt_cad' => '2023/08/22',
            ],
            [
                'prod_cod'    => 'PRD010',
                'prod_nome'   => 'Fonte 750W 80 Plus',
                'prod_cat'    => 'COMPONENTES',
                'prod_subcat' => 'FONTES',
                'prod_desc'   => 'Modular, certificação Gold',
                'prod_fab'    => 'PowerMax',
                'prod_mod'    => 'PM-750G',
                'prod_cor'    => 'Preta',
                'prod_peso'   => '2.1kg',
                'prod_larg'   => '16cm',
                'prod_alt'    => '15cm',
                'prod_prof'   => '8.6cm',
                'prod_und'    => 'UN',
                'prod_atv'    => true,
                'prod_dt_cad' => '2024-02-10',
            ],
            [
                'prod_cod'    => 'PRD011',
                'prod_nome'   => 'Gabinete Gamer',
                'prod_cat'    => 'ACESSORIOS',
                'prod_subcat' => 'GABINETES',
                'prod_desc'   => 'Mid Tower, com lateral em vidro',
                'prod_fab'    => 'CaseMaster',
                'prod_mod'    => 'CM-T500',
                'prod_cor'    => 'Branco',
                'prod_peso'   => '6.5kg',
                'prod_larg'   => '47cm',
                'prod_alt'    => '50cm',
                'prod_prof'   => '22cm',
                'prod_und'    => 'UN',
                'prod_atv'    => true,
                'prod_dt_cad' => '2023.12.05',
            ],
            [
                'prod_cod'    => 'PRD012',
                'prod_nome'   => 'Water Cooler 240mm',
                'prod_cat'    => 'COMPONENTES',
                'prod_subcat' => 'REFRIAMENTO',
                'prod_desc'   => 'Radiador duplo, RGB',
                'prod_fab'    => 'CoolFlow',
                'prod_mod'    => 'CF-W240',
                'prod_cor'    => 'Preto',
                'prod_peso'   => '1.1kg',
                'prod_larg'   => '27.5cm',
                'prod_alt'    => '12cm',
                'prod_prof'   => '5.2cm',
                'prod_und'    => 'UN',
                'prod_atv'    => false,
                'prod_dt_cad' => '2024/03/18',
            ],
        ]);
    }
}
